# config/meta.yml

meta_product_name: "Bestneighbor"
meta_title: "Bestneighbor - petits services entre voisins"
meta_description: "Services entre voisins - courses et covoiturage - et plus à venir !"
meta_image: "background.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@bestneighbor67"              # indispensable pour les Twitter Cards
