# config/meta.yml

meta_product_name: "Bestneighbor"
meta_title: "Bestneighbor - services entre voisins"
meta_description: "Services entre voisins - courses et covoiturage"
meta_image: "city-2042634_960_720.png"          # Une image dans votre dossier app/assets/images/
twitter_account: "@bestneighbor67"              # indispensable pour les Twitter Cards
